//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace orclHR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hrEntities : DbContext
    {
        public hrEntities()
            : base("name=hrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COUNTRIES> COUNTRIES { get; set; }
        public DbSet<DEPARTMENTS> DEPARTMENTS { get; set; }
        public DbSet<EMPLOYEES> EMPLOYEES { get; set; }
        public DbSet<JOB_HISTORY> JOB_HISTORY { get; set; }
        public DbSet<JOBS> JOBS { get; set; }
        public DbSet<LOCATIONS> LOCATIONS { get; set; }
        public DbSet<REGIONS> REGIONS { get; set; }
        public DbSet<EMP_DETAILS_VIEW> EMP_DETAILS_VIEW { get; set; }
    }
}
